language: node_js
node_js:
  - "10.15.3"
services:
  - postgresql
addons:
  postgresql: "10.7"
before_script:
  - psql -c 'create database banka_test;' -U postgres
after_success:
  - npm run coverage
  - npm run report
