language: node_js
node_js:
  - '10.15.3'
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
env:
  global:
    - PGPORT=5433

before_script: sudo -u postgres psql -p 5432 -h 127.0.0.1

createdb -p 5432 -h 127.0.0.1
  - psql -c 'create database banka_test;' -U postgres -p 5432 -h 127.0.0.1
after_success:
  - npm run coverage
  - npm run report
