language: node_js
node_js:
  - '10.16'
services:
  - postgresql
addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5432

before_script:
  - psql -c 'create database banka_test;' -U postgres
after_success:
  - npm run coverage
  - npm run report
